*:focus {
    outline: none !important;
}

*,
::after,
::before {
    box-sizing: content-box;
}

.nbsInput .form-control,
::after,
::before {
    box-sizing: border-box;
}

.nepFormInput {
    max-width: 1280px;
    margin-left: auto;
    margin-right: auto;
}

.formPreviewMobile {
    max-width: 400px;
    margin-left: auto;
    margin-right: auto;
}

.formPreviewTablet {
    max-width: 800px;
    margin-left: auto;
    margin-right: auto;
}

.formPreviewDesktop {
    max-width: 1280px;
    margin-left: auto;
    margin-right: auto;
}

.formPreviewFull {
    max-width: 100%;
    margin-left: auto;
    margin-right: auto;
}

.formElementButton {
    margin-left: 12px !important;
    margin-right: 10px !important;
}

.formBorder {
    border: 1px solid #ced4da;
}

.formToolbar.sapMTB.sapMTBStandard {
    border-radius: 6px;
    background: #f8f9fa;
    border: 1px solid #ced4da;
}

.form-control {
    border-radius: 8px;
}

.sapMColumnHeaderContent {
    width: 100%;
}