*:focus {
    outline: none !important;
}

.splitDesigner .sapUiFormContainerTitle>.sapUiFormTitleH1,
.splitDesigner .sapUiFormContainerTitle>.sapUiFormTitleH2,
.splitDesigner .sapUiFormContainerTitle>.sapUiFormTitleH3,
.splitDesigner .sapUiFormContainerTitle>.sapUiFormTitleH4,
.splitDesigner .sapUiFormContainerTitle>.sapUiFormTitleH5,
.splitDesigner .sapUiFormContainerTitle>.sapUiFormTitleH6 {
    font-size: 1.2rem;
}

.formNoPadding .sapMListTblHighlightCol+.sapMListTblHeaderCell,
.formNoPadding .sapMListTblHighlightCell+.sapMListTblCell {
    padding: 0
}

.nepFormInput {
    max-width: 1280px;
    margin-left: auto;
    margin-right: auto;
}

.formHeaderTitle {
    border-bottom: 1px solid #ced4da;
    border-radius: 0;
}

.formGeneral .sapUiFormResGrid>div {
    padding-bottom: 10px !important;
}

.formSettings .sapUiFormResGrid>div {
    padding-top: 0 !important;
}

.formPreviewMobile {
    max-width: 400px;
    margin-left: auto;
    margin-right: auto;
}

.formPreviewTablet {
    max-width: 800px;
    margin-left: auto;
    margin-right: auto;
}

.formPreviewDesktop {
    max-width: 1280px;
    margin-left: auto;
    margin-right: auto;
}

.formPreviewFull {
    max-width: 100%;
    margin-left: auto;
    margin-right: auto;
}

.formElementButton {
    margin-left: 12px !important;
    margin-right: 10px !important;
}

.formBorder {
    border: 1px solid #ced4da;
}

.formToolbar.sapMTB.sapMTBStandard {
    border-radius: 6px;
    background: #f8f9fa;
    border: 1px solid #ced4da;
}

.sapMColumnHeaderContent {
    width: 100%;
}