let oDraggedControl = oEvent.getParameter("draggedControl");
let oDroppedControl = oEvent.getParameter("droppedControl");

let oDraggedContext = oDraggedControl.getBindingContext();
let oDroppedContext = oDroppedControl.getBindingContext();

if (!oDraggedContext && !oDroppedContext) return;

let oDraggedData = oDraggedContext.getObject();
let oDroppedData = oDroppedContext.getObject();

let indexDrag = 0;
let indexDrop = 0;

oDroppedData.elements.push(oDraggedData);
oDroppedData.countElements = oDroppedData.elements.length;

ModelData.Delete(modeloPageElements.oData.elements,"id",oDraggedData.id);

modeloPageElements.refresh();
