const parent = controller.getParentFromId(modelpanTopProperties.oData.id);
const newElement = JSON.parse(JSON.stringify(modelpanTopProperties.oData));
let elementIndex = 0;

if (modelpanTopProperties.oData.option === "P") {
    modeloPageDetail.oData.setup.forEach(function (section, i) {
        if (section.id === modelpanTopProperties.oData.id) elementIndex = i + 1;
    });

    newElement.id = ModelData.genID();
    newElement.title = newElement.title + " (COPY)";

    newElement.elements.forEach(function (element, i) {
        element.id = ModelData.genID();
        element.title = element.title + " (COPY)";

        if (element.items) {
            element.items.forEach(function (items) {
                items.id = ModelData.genID();
            });
        }
    });

    modeloPageDetail.oData.setup.splice(elementIndex, 0, newElement);
} else {
    parent.elements.forEach(function (element, i) {
        if (element.id === modelpanTopProperties.oData.id) elementIndex = i + 1;
    });

    newElement.id = ModelData.genID();
    newElement.title = newElement.title + " (COPY)";

    if (newElement.items) {
        newElement.items.forEach(function (items) {
            items.id = ModelData.genID();
        });
    }

    parent.elements.splice(elementIndex, 0, newElement);
}

modeloPageDetail.refresh();
controller.selectObjectFromId(newElement.id);
