let oDraggedControl = oEvent.getParameter("draggedControl");
let oDroppedControl = oEvent.getParameter("droppedControl");

let oDraggedContext = oDraggedControl.getBindingContext();
let oDroppedContext = oDroppedControl.getBindingContext();

if (!oDraggedContext && !oDroppedContext) return;

const position = oEvent.getParameter("dropPosition");

let oDraggedData = oDraggedContext.getObject();
let oDroppedData = oDroppedContext.getObject();

let indexDrag = 0;
let indexDrop = 0;

let oDraggedParent;
let oDroppedParent;

modeloPageDetail.oData.setup.forEach(function (section, i) {
    if (section.id === oDraggedData.id) {
        oDraggedParent = section;
        indexDrag = i;
    }

    if (section.id === oDroppedData.id) {
        oDroppedParent = section;
        indexDrop = i;
    }

    section.elements.forEach(function (element, i) {
        if (element.id === oDraggedData.id) {
            oDraggedParent = section;
            indexDrag = i;
        }

        if (element.id === oDroppedData.id) {
            oDroppedParent = section;
            indexDrop = i;
        }
    });
});

// FORM - TOP
if (oDraggedData.elements && oDroppedData.elements) {
    Utils.arrayMove(modeloPageDetail.oData.setup, indexDrag, indexDrop);
}

if (oDraggedData.elements && !oDroppedData.elements) {
    return;
}

if (!oDraggedData.elements && oDroppedData.elements) {
    if (oDraggedParent.id === oDroppedParent.id) {
        Utils.arrayMove(oDroppedParent.elements, indexDrag, 0);
    } else {
        oDroppedParent.elements.splice(indexDrop, 0, oDraggedData);
        ModelData.Delete(oDraggedParent.elements, "id", oDraggedData.id);
    }
}

if (!oDraggedData.elements && !oDroppedData.elements) {
    if (oDraggedParent.id === oDroppedParent.id) {
        Utils.arrayMove(oDroppedParent.elements, indexDrag, indexDrop);
    } else {
        oDroppedParent.elements.splice(indexDrop, 0, oDraggedData);
        ModelData.Delete(oDraggedParent.elements, "id", oDraggedData.id);
    }
}

modeloPageDetail.refresh(true);
controller.selectObjectFromId(oDraggedData.id);