const context = oEvent.oSource.getBindingContext();
const newElement = JSON.parse(JSON.stringify(context.getObject()));

const elementIndex = parseInt(context.sPath.split("/")[2]) + 1;

newElement.id = ModelData.genID();
newElement.title = newElement.title + " (COPY)";

newElement.elements.forEach(function (element) {
    element.id = ModelData.genID();
});

modeloPageDetail.oData.setup.splice(elementIndex, 0, newElement);
modeloPageDetail.refresh();
